DROP TABLE IF EXISTS `users`;

CREATE TABLE users (
	NM_USERNAME varchar(45) NOT NULL,
	NM_PASSWORD varchar(45) NOT NULL,
	ENABLED TINYINT NOT NULL DEFAULT 1,
	PRIMARY KEY (NM_USERNAME)
);

DROP TABLE IF EXISTS `user_roles`;

CREATE TABLE user_roles (
	USER_ROLE_ID int(11) NOT NULL AUTO_INCREMENT,
	NM_USERNAME varchar(45) NOT NULL,
	NM_ROLE varchar(45) NOT NULL,
	PRIMARY KEY (USER_ROLE_ID),
	UNIQUE KEY UNI_USERNAME_ROLE (NM_ROLE,NM_USERNAME),
	KEY FK_USERNAME_IDX (NM_USERNAME),
	CONSTRAINT FK_USERNAME FOREIGN KEY (NM_USERNAME) REFERENCES users (NM_USERNAME)
);

DROP TABLE IF EXISTS `team`;


CREATE TABLE `team`
(
ID int PRIMARY KEY AUTO_INCREMENT,
NM_NAME varchar(100),
NM_EMBLEM varchar(300)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `position`;

CREATE TABLE `position`
(
ID int PRIMARY KEY AUTO_INCREMENT,
NM_NAME varchar(100)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `player`;

CREATE TABLE `player`
(
ID int PRIMARY KEY AUTO_INCREMENT,
NM_PHOTO varchar(300),
NM_NAME varchar(100),
AGE int,
POWER int,
TECNIQUE int,
ID_POSITION int,
DT_BIRTHDAY date DEFAULT NULL,
BEST_LEG bit(1) DEFAULT 0 NOT NULL,
FOREIGN KEY (`ID_POSITION`) REFERENCES `position` (`ID`)
)ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

INSERT INTO player(NM_NAME, AGE, POWER, TECNIQUE) VALUES ('deivide',23,78,80), ('player1',21,70,76);
INSERT INTO users(NM_USERNAME, NM_PASSWORD, ENABLED) VALUES ('dpossamai','dpossamai',true), ('user1','user1',true);
INSERT INTO user_roles(NM_USERNAME, NM_ROLE) VALUES ('dpossamai','ROLE_USER'),  ('dpossamai','ROLE_ADMIN'), ('user1','ROLE_USER');

INSERT INTO team(NM_NAME) VALUES ('team1'), ('team2'), ('team3');